configuration: Debug
image: Visual Studio 2022

version: '{build}'

init:
- ps: Update-AppveyorBuild -Version "$($env:ospsuite_version).$($env:appveyor_build_version)"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(ospsuite_version).$(build_number)'
  assembly_version: '$(ospsuite_version).$(build_number)'
  file_version: '$(ospsuite_version).$(build_number)'
  informational_version: '$(ospsuite_version).$(build_number)'

install:
- set PATH=C:\Ruby25\bin;%PATH%

before_build:
  - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
  - nuget sources add -name core -source https://ci.appveyor.com/nuget/ospsuite-core
  - nuget sources add -name serializer -source https://ci.appveyor.com/nuget/ospsuite-serializer
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes
  - nuget restore

after_build:
  - rake "create_portable_setup[%APPVEYOR_BUILD_VERSION%, %CONFIGURATION%, qualificationrunner-portable-setup.zip]"

build:
  verbosity: minimal
  project: QualificationRunner.sln

on_finish: 
  - ps: Get-ChildItem .\setup\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
skip_tags: true

skip_commits:
  files:
    - "**/*.md"